apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nginx-chart.selectorLabels" . | nindent 8 }}
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer




















